name: Report

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.workflow_run.conclusion }}
      - run: echo ${{ github.event.workflow_run }}
