name: Report

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  report:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.workflow_run.conclusion }}
      - run: echo '${{ toJSON(github.event.workflow_run) }}'
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
          message: 'Comment from a workflow'
